jwt:
  secret: ${JWT_SECRET:1ed9e4e637cef80e7f5e21d5f28c9853b2aee451f5da1f8a2a1aacf2602c34d7}

google:
  client-id: ${GOOGLE_CLIENT_ID:772988401705-4io9tviphr75k075kb9lbrnmn960h2r8.apps.googleusercontent.com}

spring:
  doc:
    api-docs:
      path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/manitto}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:word1234}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:hi.urssu@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:anki dsjw nmes cieq}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8080}
